---
title: AMIR
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
SEOTitle: پسرک کامپیوترپیشه
header-img: img/home-bg.jpg
email: amiremohamadi@yahoo.com
description: ''
keyword: ''
url: http://mamir.me
RSS: false
telegram_username: amiremohamadi
# mail_username: amiremohamadi@yahoo.com
github_username: amiremohamadi
instagram_username: amiremohamadi
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
anchorjs: true
plugins:
- jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
ga_track_id: UA-49627206-1
ga_domain: mamir.me
sidebar: true
sidebar-about-description:  مطالبی که میخوانید حاصل ذهن مغشوش یک دانشجوی کامپیوتر بوده و مسئولیت هرگونه خطای احتمالی، به عهده ساکنین سیاره "کپلر ۶۹ سی" میباشد! 
sidebar-avatar: "/img/avatar-hux.png"
friends:
- title: کیبرد آزاد
  href: "#"
- title: سحر شاکر
  href: "#"
- title: صدرا علی آبادی
  href: "#"
- title: سالار کابلی
  href: "#"
